### ISSUE TITLE
AddRange in #144 Binary tree pre-order traversal

### ISSUE THREAD

**Issue by Mooophy** [scottszb1987/LeetCodeInCSharp#2]
Please notice the semantics of method `AddRange`. Basically, it **copies** items from source collections. The source items will be reclaimed by CLR some time later. So the current implementation in this repo wastes a lot of spaces. 

Like following, I wrote another implementation using `Concat` to reduce this overhead.

``` csharp
    public IList<int> PreorderTraversal(TreeNode root) 
    {
        if (root == null) 
            return new List<int>();
        else
            return new List<int>{ root.val }
                .Concat(PreorderTraversal(root.left))
                .Concat(PreorderTraversal(root.right))
                .ToList();
    }
```

**Comment by Mooophy** [comment]
Another thing to note:
Since `List` in C# is essentially dynamic array, probably `Concat` could cause to reallocation. As C# has no support to move semantics, when reallocation happens we can not avoid all unnecessary copies. So perhaps the code above should use `LinkedList` rather than `List`. `LinkedList` can remove all unnecessary copies, and implement interface `IList` as well.

**Comment by bysz71** [comment]
That make great sense, I'll update it. BTW, assuming it still returns a `List`, and it implements `IList<>` interface, when I have something like `var list = PreorderTraversal(root);`, this `list` in here cannot use the `List` APIs that are not defined in `IList<>` interface. Is there any way to solve this issue?

**Comment by bysz71** [comment]
Well are you sure `Concat` does not copy stuff? is it truly more space-wise efficient than `AddRange`?

**Comment by Mooophy** [comment]
Try this:

``` cpp
(list as List<int>).MethodNotDefinedInIList()
```

**Comment by bysz71** [comment]
Well yes, it is well answered [SO link](https://stackoverflow.com/questions/100196/net-listt-concat-vs-addrange). Now I get it.

**Comment by bysz71** [comment]
OK, or maybe `ToList()`? Whats the syntax you are using? that `something as sometype`

**Comment by Mooophy** [comment]
As goes in MSDN:

> The as operator is like a cast operation. However, if the conversion isn't possible, as returns null instead of raising an exception. 

We can compare `as` to casting in C: 

``` c
int i = 42;
long j = 999999999999;
i = (int)j;
```

The different part is that `as` in c# only casts when possible.
IMHO `as` is quite cheap, because it's casting a reference to another rather than copy everything like `ToList` does. But one thing we need keep in mind is that `as` could fail whereas `ToList` is safer.
