### ISSUE TITLE
Complexity Analysis of 13 Roman to Integer

### ISSUE THREAD

**Issue by Mooophy** [scottszb1987/LeetCodeInCSharp#4]
Please note the fact that the size of the dictionary you used, which has been deleted in a8627ed46a5389a68d5b5e8949301dd46d096d3e, has nothing to do with argument size. Hence the solution using dictionaries takes only O(1) time and O(1) extra space. Actually, as used in the current implementation, multiple `if else` statements are considered to be slower than Hash Table and `switch` cases statement.  Basically, `if else` takes O(n) time. A reference can be found here : [If else vs switch on SO](http://stackoverflow.com/questions/395618/is-there-any-significant-difference-between-using-if-else-and-switch-case-in-c).

That said, the version deleted in a8627ed46a5389a68d5b5e8949301dd46d096d3e still can be improved, because dictionaries are good at lookup rather than iteration, wherras array (i.e. String `s`) good at iteration rather than lookup.

I implemented another version with same idea as that deleted, like following:

``` csharp
public class Solution 
{
    public int RomanToInt(string s) 
    {
        var twos = new Dictionary<string, int>()
        {
             { "CM", 900 }, { "CD", 400 }, { "XC", 90 }, { "XL", 40 }, { "IX", 9 }, { "IV", 4 }
        };
        var ones = new Dictionary<string, int>()
        {
            { "I", 1 }, { "V", 5 }, { "X", 10 }, { "L", 50 }, { "C", 100 }, { "D", 500 }, { "M", 1000 }
        };

        int sum = 0;
        for(int i = 0; i < s.Length;)
        {
            if(i + 1 == s.Length || !twos.ContainsKey(s.Substring(i, 2)))
            {
                sum += ones[s[i].ToString()];
                i += 1;
            }
            else
            {
                sum += twos[s.Substring(i, 2)];
                i += 2;
            }
        }
        return sum;
    }
}
```

**Comment by bysz71** [comment]
Beautiful solution

**Comment by bysz71** [comment]
and good point on switc/if
